# Generated by Django 4.2.23 on 2025-08-09 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotitem',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chatbots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatbotitem',
            name='background',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='chatbotitem',
            name='gender',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='chatbotitem',
            name='name',
            field=models.CharField(max_length=225, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='chatbotitem',
            name='personality',
            field=models.CharField(max_length=225, null=True, unique=True),
        ),
    ]
