# Generated by Django 4.2.23 on 2025-08-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_chatbotitem_created_by_alter_chatbotitem_background_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotitem',
            name='favourite_food',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='chatbotitem',
            name='hobbies',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='chatbotitem',
            name='quirks',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
