# Generated by Django 4.2.23 on 2025-08-09 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_chatbotitem_favourite_food_chatbotitem_hobbies_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatbotitem',
            old_name='favourite_food',
            new_name='favorite_food',
        ),
    ]
