# Generated by Django 4.2.23 on 2025-08-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_rename_favourite_food_chatbotitem_favorite_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbotitem',
            name='personality',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
